version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      pip-minor-patch:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
